from rest_framework import serializers


class ListeningGenerateRequestSerializer(serializers.Serializer):
    difficulty = serializers.ChoiceField(
        choices=['easy', 'medium', 'hard'],
        default='medium',
        required=False,
        help_text="Difficulty level of the generated sentence."
    )


class ListeningEvaluateRequestSerializer(serializers.Serializer):
    original_sentence = serializers.CharField(
        required=True,
        help_text="The original sentence generated by AI (that the user was asked to repeat)."
    )
    user_response = serializers.CharField(
        required=True,
        help_text="The text of what the user said (from speech-to-text on the frontend)."
    )
